# ********RoostGPT********
"""
Test generated by RoostGPT for test raghu-python-test1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test raghu-python-test1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=month_days_1396fdc0ba
ROOST_METHOD_SIG_HASH=month_days_5dd3c5e333


Scenario 1: Validate the number of days in January (should be 31, regardless of leap year)
Details:
  TestName: test_January_days
  Description: This test verifies that the function consistently returns 31 days for January, irrespective of the leap_year boolean.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 1, true and 1, false.
  Assert: The function should return 31 in either case.
Validation:
  This tests the inherent business rule that January always has 31 days irrespective of whether the year is a leap year or not.

Scenario 2: Validate the number of days in February in a leap year (should be 29)
Details:
  TestName: test_February_days_leap_year
  Description: This test verifies the function correctly identifies that February has 29 days in a leap year.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 2, true
  Assert: The function should return 29.
Validation:
  This tests the inherent business rule that February has 29 days in a leap year.

Scenario 3: Validate the number of days in February in a non-leap year (should be 28)
Details:
  TestName: test_February_days_nonleap_year
  Description: This test verifies the function correctly identifies that February has 28 days in a non leap year.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 2, false
  Assert: The function should return 28.
Validation:
  This tests the inherent business rule that February has 28 days in a non-leap year.

Scenario 4: Validate the number of days in April (should be 30, regardless of leap year)
Details:
  TestName: test_April_days
  Description: This test verifies that the function consistently returns 30 days for April, irrespective of the leap_year boolean.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 4, true and 4, false.
  Assert: The function should return 30 in either case.
Validation:
  This tests the inherent business rule that April has 30 days irrespective of whether the year is a leap year or not.

Scenario 5: Validate the number of days in December (should be 31, regardless of leap year)
Details:
  TestName: test_December_days
  Description: This test verifies that the function consistently returns 31 days for December, irrespective of the leap_year boolean.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 12, true and 12, false.
  Assert: The function should return 31 in either case.
Validation:
  This tests the inherent business rule that December always has 31 days irrespective of whether the year is a leap year or not.
  
Scenario 6: Negative case for invalid month number (> 12 or < 1)
Details:
  TestName: test_invalid_month
  Description: This test verifies the function's behavior when supplied with an invalid month value.
Execution:
  Arrange: No specific setup is required.
  Act: Invoke the function with parameters 13, true and -1, false.
  Assert: The function might throw an exception or return null (this depends on the desired functionality, as the behavior on invalid input is not specified in the problem description).
Validation:
  This tests the edge case of the function, ensuring that it can either handle invalid inputs gracefully (by throwing an exception or returning a certain value), or that it correctly neglects them if they are not part of the input domain.
"""

# ********RoostGPT********
import pytest
from calculate import month_days

class Test_CalculateMonthDays:

    @pytest.mark.parametrize("month, leap_year, expected", [(1, True, 31), (1, False, 31)])
    def test_January_days(self, month, leap_year, expected):
        assert month_days(month, leap_year) == expected

    @pytest.mark.parametrize("month, leap_year, expected", [(2, True, 29)])
    def test_February_days_leap_year(self, month, leap_year, expected):
        assert month_days(month, leap_year) == expected

    @pytest.mark.parametrize("month, leap_year, expected", [(2, False, 28)])
    def test_February_days_nonleap_year(self, month, leap_year, expected):
        assert month_days(month, leap_year) == expected

    @pytest.mark.parametrize("month, leap_year, expected", [(4, True, 30), (4, False, 30)])
    def test_April_days(self, month, leap_year, expected):
        assert month_days(month, leap_year) == expected

    @pytest.mark.parametrize("month, leap_year, expected", [(12, True, 31), (12, False, 31)])
    def test_December_days(self, month, leap_year, expected):
        assert month_days(month, leap_year) == expected

    @pytest.mark.parametrize("month, leap_year", [(13, True), (-1, False)])
    def test_invalid_month(self, month, leap_year):
        with pytest.raises(ValueError):
            month_days(month, leap_year)
